// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADrdecE4FeJi3bloQfw2v-t-qodU-Mb70',
    appId: '1:772774871205:android:3b98c861edce9c6b574d4c',
    messagingSenderId: '772774871205',
    projectId: 'hahaton-2bbfc',
    storageBucket: 'hahaton-2bbfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx-7l-Dol9grZ8-4_0kuQoR5KwKDnrllI',
    appId: '1:772774871205:ios:ce575907f142fbb3574d4c',
    messagingSenderId: '772774871205',
    projectId: 'hahaton-2bbfc',
    storageBucket: 'hahaton-2bbfc.appspot.com',
    androidClientId: '772774871205-0e7hanto6cfrbloars3j374qn85slunf.apps.googleusercontent.com',
    iosClientId: '772774871205-sqrlqq9tdjoh4lg1diono3gj880qdohf.apps.googleusercontent.com',
    iosBundleId: 'com.polienova.kotlov.int20h.int20h',
  );
}
